SWEP.Base				= "draconic_melee_base"
SWEP.Gun				= "drc_knife"

SWEP.HoldType			= "knife" -- https://wiki.garrysmod.com/page/Hold_Types
SWEP.CrouchHoldType		= "knife"
SWEP.IdleSequence		= "idle"
SWEP.WalkSequence		= "idle"
SWEP.Category			= "Draconic: Halo Lore Expansions"
SWEP.PrintName			= "Jiralhanae Combat Knife"
SWEP.InfoName			= "knife"
SWEP.Auhtor				= "Vuthakral"
SWEP.Contact			= " https://discord.gg/6Y7WXrX // Steam: Vuthakral // Disc: Vuthakral#9761 "
SWEP.Purpose			= ""
SWEP.Instructions		= ""
 
SWEP.Spawnable      = true
SWEP.AdminSpawnable = false
SWEP.DrawCrosshair  = true
SWEP.Slot           = 0
SWEP.SlotPos        = 1

SWEP.UseHands		= true
SWEP.DoesPassiveSprint = false
SWEP.ViewModel 		= "models/vuthakral/halo/weapons/c_knife_brute.mdl"
SWEP.WorldModel 	= "models/vuthakral/halo/weapons/w_knife_brute.mdl"
SWEP.ViewModelFOV   = 70
SWEP.VMPos 			= Vector(0, 2.5, -1)
SWEP.VMAng 			= Vector(0, 0, 0)
SWEP.VMPosCrouch 	= Vector(0, 2, -2)
SWEP.VMAngCrouch 	= Vector(0, 0, 0)
SWEP.SS 			= 1
SWEP.BS 			= 1

SWEP.IdleActivity = ACT_VM_IDLE
SWEP.CrouchIdleActivity = ACT_VM_IDLE

SWEP.ViewModelFlip  = false

SWEP.Primary.SwingSound		= Sound( "draconic.BladeSwingSmall" )
SWEP.Primary.HitSoundWorld 	= Sound( "draconic.BladeSmallHitWorld" )
SWEP.Primary.HitSoundFlesh 	= Sound( "draconic.BladeSmallHitFlesh" )
SWEP.Primary.HitSoundEnt 	= Sound( "draconic.BladeSmallHitWorld" )
SWEP.Primary.HoldType		= "knife"
SWEP.Primary.HoldTypeCrouch	= "knife"
SWEP.Primary.ImpactDecal 	= "ManhackCut"
SWEP.Primary.Automatic		= true
SWEP.Primary.Damage			= 7
SWEP.Primary.DamageType		= DMG_SLASH
SWEP.Primary.Range			= 20
SWEP.Primary.Force			= 5
SWEP.Primary.DelayMiss		= 0.42
SWEP.Primary.DelayHit 		= 0.54
SWEP.Primary.CanAttackCrouched = true
SWEP.Primary.MissActivity	= ACT_VM_PRIMARYATTACK 
SWEP.Primary.CrouchMissActivity	= ACT_VM_PRIMARYATTACK 
SWEP.Primary.HitDelay		= 0.14
SWEP.Primary.StartX			= 20
SWEP.Primary.StartY			= 2.5
SWEP.Primary.EndX			= -20
SWEP.Primary.EndY			= -2.5

SWEP.Primary.CanLunge			= true
SWEP.Primary.LungeAutomatic		= false
SWEP.Primary.LungeVelocity		= 1000
SWEP.Primary.LungeMaxDist		= 150
SWEP.Primary.LungeSwingSound	= Sound( "draconic.BladeStabSmall" )
SWEP.Primary.LungeHitSoundWorld = Sound( "draconic.BladeSmallHitWorld" )
SWEP.Primary.LungeHitSoundFlesh = Sound( "draconic.BladeSmallStabFlesh" )
SWEP.Primary.LungeHitSoundEnt	= Sound( "draconic.BladeSmallHitWorld" )
SWEP.LungeHoldType		= "melee"
SWEP.LungeHoldTypeCrouch		= "melee"
SWEP.Primary.LungeImpactDecal 	= "ManhackCut"
SWEP.Primary.LungeMissAct		= ACT_VM_HITCENTER
SWEP.Primary.LungeDelayMiss		= 1.3
SWEP.Primary.LungeDelayHit		= 0.7
SWEP.Primary.LungeHitDelay		= 0.26
SWEP.Primary.LungeDamage		= 72
SWEP.Primary.LungeDamageType	= DMG_SLASH
SWEP.Primary.LungeRange			= 25
SWEP.Primary.LungeForce			= 20
SWEP.Primary.LungeStartX		= 30
SWEP.Primary.LungeEndX			= -30
SWEP.Primary.LungeStartY		= -2.5
SWEP.Primary.LungeEndY			= 2.5

SWEP.Secondary.SwingSound		= Sound( "draconic.BladeSwingSmall" )
SWEP.Secondary.HitSoundWorld 	= Sound( "draconic.BladeSmallHitWorld" )
SWEP.Secondary.HitSoundFlesh 	= Sound( "draconic.BladeSmallHitFlesh" )
SWEP.Secondary.HitSoundEnt 		= Sound( "draconic.BladeSmallHitWorld" )
SWEP.Secondary.HoldType			= "knife"
SWEP.Secondary.HoldTypeCrouch	= "knife"
SWEP.Secondary.ImpactDecal 		= "ManhackCut"
SWEP.Secondary.Automatic		= true
SWEP.Secondary.Damage			= 7
SWEP.Secondary.DamageType		= DMG_SLASH
SWEP.Secondary.Range			= 20
SWEP.Secondary.Force			= 5
SWEP.Secondary.DelayMiss		= 0.42
SWEP.Secondary.DelayHit 		= 0.54
SWEP.Secondary.CanAttackCrouched = true
SWEP.Secondary.MissActivity		= ACT_VM_SECONDARYATTACK 
SWEP.Secondary.CrouchMissActivity	= ACT_VM_SECONDARYATTACK 
SWEP.Secondary.HitDelay			= 0.14
SWEP.Secondary.StartX			= -20
SWEP.Secondary.StartY			= 2.5
SWEP.Secondary.EndX				= 20
SWEP.Secondary.EndY				= -2.5